import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ events }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About-Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {events.map((event) => {
          return (
            <a href={`/events/${event.id}`} key={event.id}>
              <div>
                <img
                  src={event.image}
                  width={200}
                  height={300}
                  alt={event.title}
                />
                <h2>{event.title}</h2>
                <p>{event.description}</p>
              </div>
            </a>
          );
        })}
      </main>
      <footer className={styles.footer}></footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('../../data/data.json');

  return {
    props: {
      events: events_categories,
      title: 'Events Page happy day!',
    },
  };
}
